#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import logging
import subprocess

_logger = logging.getLogger(__name__)


SOURCES = str(os.environ.get("SOURCES"))
CUSTOM = str(os.path.join(SOURCES, "custom"))
RESOURCES = str(os.environ.get("RESOURCES"))

addons = []

# Extrae los addons de las carpetas en /sources excepto custom
for d in sorted(os.listdir(SOURCES)):
    full_path = os.path.join(SOURCES, d)
    if os.path.isdir(full_path) and full_path != CUSTOM:
        addons.insert(0, full_path)


# Project repositories
repo_addons = []

# Custom repositories, usually mounted for development
if os.path.isdir(CUSTOM):
    repo_addons += [
        os.path.join(CUSTOM, d)
        for d in sorted(os.listdir(CUSTOM))
        if os.path.isdir(os.path.join(CUSTOM, d))
    ]

    for d in sorted(os.listdir(CUSTOM)):
        module_path = os.path.join(CUSTOM, d)
        requirement_file = os.path.join(module_path, "requirements.txt")
        if os.path.exists(requirement_file):
            subprocess.check_call(
                [
                    "pip",
                    "install",
                    # "--user",
                    "--no-cache-dir",
                    "-r",
                    requirement_file,
                ]
            )

# Repo addons are preprended, in case we want to overwrite odoo modules
addons = repo_addons + addons

# Overwrite 10-addons.conf
_logger.debug("Updating addons_path.. %s" % addons)
with open(os.path.join(RESOURCES, "conf.d", "10-addons.conf"), "w+") as file:
    file.write("[options]\naddons_path = %s" % ",".join(addons))
