"""
Generates docker-compose.generated.yml from instances.json configuration.
Creates services for managed databases, Odoo instances, nginx, and optionally pgAdmin.
"""

import os
import re

from .config_loader import (
    resolve_instance_config,
    resolve_db_config,
    get_db_host,
    get_db_internal_port,
    get_managed_databases,
    get_odoo_minor,
    is_production_instance,
)

# Internal ports used by Odoo (never exposed directly; nginx proxies them)
ODOO_HTTP_PORT = 8069
ODOO_GEVENT_PORT = 8071

NETWORK_NAME = "odoo-multi"

# MailHog defaults (used when config omits the mailhog section or specific fields)
MAILHOG_SERVICE_NAME = "mailhog"
MAILHOG_DEFAULT_SMTP_PORT = 1025


def _project_slug(base_path):
    """
    Derive a stable per-checkout token from the containing directory name.

    Docker image names/tags are a *global* namespace on the host — unlike
    container names, networks, and volumes, they are never scoped by Docker
    Compose's project name. Two separate docker-odoo checkouts that reuse the
    same `database` key or instance name (e.g. both use "v17") would otherwise
    build and overwrite the exact same local image tag on `./odoo build`.
    Prefixing with this slug keeps images distinct per checkout, mirroring how
    Compose already scopes everything else by directory name.
    """
    name = os.path.basename(os.path.abspath(base_path))
    name = re.sub(r"[^a-z0-9_.-]+", "-", name.lower()).strip("-")
    return name or "docker-odoo"


def generate_compose(base_path, config, dockerfile_map):
    """
    Generate docker-compose.generated.yml.
    Returns the output file path.
    """
    lines = _header()
    project = _project_slug(base_path)

    # --- Database services ---
    managed_dbs = get_managed_databases(config)
    for db_name, db_conf in managed_dbs.items():
        lines += _db_service(db_name, db_conf, project)

    # --- Odoo instance services ---
    mailhog_conf = config.get("mailhog", {}) if config.get("mailhog", {}).get("enabled", False) else None
    for inst_name, inst_conf in config["instances"].items():
        odoo_conf = resolve_instance_config(inst_conf, config)
        db_conf = resolve_db_config(inst_conf, config)
        db_name = inst_conf["database"]
        odoo_version = inst_conf["odoo_version"]
        dockerfile = dockerfile_map[odoo_version]
        lines += _odoo_service(
            inst_name, inst_conf, odoo_conf, db_name, db_conf, dockerfile, mailhog_conf, project
        )

    # --- Nginx service ---
    lines += _nginx_service(config)

    # --- pgAdmin service (optional) ---
    pgadmin_conf = config.get("pgadmin", {})
    if pgadmin_conf.get("enabled", False):
        lines += _pgadmin_service(pgadmin_conf)

    # --- MailHog service (optional) ---
    mailhog_conf = config.get("mailhog", {})
    if mailhog_conf.get("enabled", False):
        lines += _mailhog_service(mailhog_conf)

    # --- Volumes ---
    lines += _volumes(config)

    # --- Networks ---
    lines += _networks()

    output_path = os.path.join(base_path, "docker-compose.generated.yml")
    with open(output_path, "w") as f:
        f.write("\n".join(lines))
        f.write("\n")

    print(f"  docker-compose.generated.yml generado")
    return output_path


def _header():
    return [
        "# Auto-generated by ./odoo build — DO NOT EDIT MANUALLY",
        "# Modify instances.json and run ./odoo build to regenerate",
        "",
        "services:",
    ]


def _db_service(db_name, db_conf, project):
    pg_version = db_conf["postgres_version"]
    port = db_conf["port"]
    # "user"/"password" are the non-superuser role Odoo actually connects with.
    # "bootstrap_user"/"bootstrap_password" (falls back to user/password if
    # absent) are the cluster's initdb bootstrap role, which Postgres always
    # creates as a superuser and never lets lose that attribute. The bootstrap
    # role is only used internally (docker-entrypoint-initdb.d) to create the
    # app role on a fresh volume; Odoo itself never authenticates as it.
    user = db_conf["user"]
    password = db_conf["password"]
    bootstrap_user = db_conf.get("bootstrap_user", user)
    bootstrap_password = db_conf.get("bootstrap_password", password)
    pg_config = db_conf.get("config")
    expose_host_port = db_conf.get("expose_host_port", False)
    container_name = f"db-{db_name}"

    lines = [
        f"  {container_name}:",
    ]

    if pg_config:
        lines += [
            f'    command: ["postgres", "-c", "config_file=/etc/postgres/dbconfigs/{pg_config}"]',
        ]

    lines += [
        "    restart: always",
        "    shm_size: 512m",
        "    build:",
        "      context: .",
        "      dockerfile: ./.resources/db.Dockerfile",
        "      args:",
        f"        POSTGRES_IMG_VERSION: {pg_version}",
        f"    image: local_odoo_db_{project}_{db_name}:{pg_version}",
    ]

    # Host port publishing is opt-in: by default Postgres is only reachable
    # from sibling containers over the internal Docker network (db-<name>:5432).
    # Set "expose_host_port": true on the database config to publish it.
    if expose_host_port:
        lines += [
            "    ports:",
            f'      - "{port}:5432"',
        ]

    lines += [
        f"    networks:",
        f"      - {NETWORK_NAME}",
        "    volumes:",
        "      - ./.resources/dbconfigs:/etc/postgres/dbconfigs",
        f"      - {db_name}-data:/var/lib/postgresql/data",
        "    environment:",
        "      - POSTGRES_DB=postgres",
        f"      - POSTGRES_PASSWORD={bootstrap_password}",
        f"      - POSTGRES_USER={bootstrap_user}",
        f"      - APP_DB_USER={user}",
        f"      - APP_DB_PASSWORD={password}",
        "      - PGDATA=/var/lib/postgresql/data/pgdata",
        "",
    ]
    return lines


def _odoo_service(inst_name, inst_conf, odoo_conf, db_name, db_conf, dockerfile, mailhog_conf, project):
    odoo_version = inst_conf["odoo_version"]
    odoo_minor = get_odoo_minor(odoo_version)
    container_name = f"odoo-{inst_name}"
    db_host = get_db_host(db_name, db_conf)
    # NOTE: db_conf["port"] is the HOST-side port (only published when
    # expose_host_port is set) — not reachable from sibling containers.
    # Odoo always talks to Postgres over the internal Docker network.
    db_port = get_db_internal_port(db_conf)
    # db_conf["user"]/["password"] are already resolved to the instance's own
    # dedicated Postgres role when set (see resolve_db_config), falling back
    # to the service-level role otherwise.
    db_user = db_conf["user"]
    db_password = db_conf["password"]
    smtp_server = mailhog_conf.get("service_name", MAILHOG_SERVICE_NAME) if mailhog_conf else MAILHOG_SERVICE_NAME
    smtp_port = mailhog_conf.get("smtp_port", MAILHOG_DEFAULT_SMTP_PORT) if mailhog_conf else MAILHOG_DEFAULT_SMTP_PORT

    # Build addons list for INSTANCE_ADDONS env var
    addons = odoo_conf.get("addons", [])
    addons_str = ",".join(addons) if addons else ""

    # Determine depends_on
    depends = []
    if db_conf.get("create_container", True):
        depends.append(f"db-{db_name}")

    # --dev=all (Odoo's autoreload/dev mode) is opt-in via odoo_conf's
    # "dev_mode", but must never reach a production instance. _validate_instance
    # already rejects that combination at config-load time; the extra check
    # here is belt-and-suspenders so a future validation bug can't silently
    # turn dev mode on in production.
    dev_mode = odoo_conf.get("dev_mode", False) and not is_production_instance(inst_conf)
    command = "odoo --dev=all" if dev_mode else "odoo"

    lines = [
        f"  {container_name}:",
        f"    command: {command}",
        "    restart: always",
        "    build:",
        "      context: .",
        f"      dockerfile: ./{dockerfile}",
        f"    image: local_odoo_{project}_{inst_name}:{odoo_minor}",
        "    extra_hosts:",
        '      - "host.docker.internal:host-gateway"',
        "    dns:",
        "      - 8.8.8.8",
        "      - 1.1.1.1",
        f"    networks:",
        f"      - {NETWORK_NAME}",
    ]

    if depends:
        lines.append("    depends_on:")
        for dep in depends:
            lines.append(f"      - {dep}")

    lines += [
        "    volumes:",
        f"      - {inst_name}-web:/var/lib/odoo",
        "      - ./src:/home/odoo/src",
        "      - ./.resources/.coveragerc:/home/odoo/.coveragerc",
        f"      - {inst_name}-data:/home/odoo/data",
        f"      - {inst_name}-py3:/usr/local/lib/",
        f"      - {inst_name}-py:/usr/lib/",
        "    environment:",
    ]

    # Custom config from odoo_conf
    custom_config = odoo_conf.get("custom_config", "[options]")
    lines.append(f"      CUSTOM_CONFIG: |-")
    for config_line in custom_config.split("\n") if isinstance(custom_config, str) else ["[options]"]:
        lines.append(f"        {config_line}")

    lines += [
        "      CUSTOM_REQUIREMENTS: |-",
        "        # custom pip libraries",
        "      CUSTOM_ENTRYPOINT: |-",
        "        #!/bin/bash",
        f"      GEVENT_PORT: {ODOO_GEVENT_PORT}",
        f"      DB_HOST: {db_host}",
        f"      DB_PORT: {db_port}",
        f"      PGUSER: {db_user}",
        f"      PGPASSWORD: {db_password}",
        f"      PGHOST: {db_host}",
        f"      PGPORT: {db_port}",
        f"      ADMIN_PASSWORD: {odoo_conf.get('admin_password', 'admin')}",
        f"      SMTP_SERVER: {smtp_server}",
        f"      SMTP_PORT: {smtp_port}",
        f"      DBFILTER: {odoo_conf.get('db_filter', '')}",
        f"      SERVER_WIDE_MODULES: {odoo_conf.get('server_wide_modules', '')}",
        f"      WORKERS: {odoo_conf.get('workers', 2)}",
        f"      LIST_DB: {odoo_conf.get('list_db', True)}",
        f"      DB_NAME: {odoo_conf.get('db_name', 'False')}",
        f"      WITHOUT_DEMO: {odoo_conf.get('without_demo', True)}",
        f"      PROXY_MODE: {odoo_conf.get('proxy_mode', True)}",
        f"      SERVER_MODE: {odoo_conf.get('server_mode', 'test')}",
        f"      AEROO_DOCS_HOST: {odoo_conf.get('aeroo_docs_host', 'aeroo')}",
        f"      UNACCENT: {odoo_conf.get('unaccent', False)}",
        "      LOG_LEVEL: info",
        f"      LIMIT_MEMORY_SOFT: {odoo_conf.get('limit_memory_soft', 16000000000)}",
        f"      LIMIT_MEMORY_HARD: {odoo_conf.get('limit_memory_hard', 17000000000)}",
        f"      MAX_CRON_THREADS: {odoo_conf.get('max_cron_threads', 1)}",
        f"      LIMIT_TIME_REAL_CRON: {odoo_conf.get('limit_time_real_cron', 0)}",
        f"      LIMIT_TIME_REAL: {odoo_conf.get('limit_time_real', 3600)}",
        f"      LIMIT_TIME_CPU: {odoo_conf.get('limit_time_cpu', 60)}",
        f"      DB_MAXCONN: {odoo_conf.get('db_maxconn', 200)}",
    ]

    # INSTANCE_ADDONS: used by the modified 400-auto-detect-addons entrypoint
    if addons_str:
        lines.append(f"      INSTANCE_ADDONS: \"{addons_str}\"")

    lines.append("")
    return lines


def _nginx_service(config):
    """Generate nginx service that maps all instance external ports."""
    all_ports = [
        inst["external_port"]
        for inst in config["instances"].values()
    ]
    odoo_containers = [
        f"odoo-{name}" for name in config["instances"]
    ]

    lines = [
        "  nginx:",
        "    restart: always",
        "    image: nginx:latest",
        # "    depends_on:",
    ]
    # for container in odoo_containers:
    #     lines.append(f"      - {container}")

    lines += [
        "    extra_hosts:",
        '      - "host.docker.internal:host-gateway"',
        "    ports:",
        '      - "80:80"',
    ]
    for port in all_ports:
        lines.append(f'      - "{port}:{port}"')

    # Expose optional service ports (pgadmin, mailhog) so users can reach
    # them via subdomain on port 80.
    pgadmin_conf = config.get("pgadmin", {})
    if pgadmin_conf.get("enabled", False):
        pg_port = pgadmin_conf.get("port", 5050)
        lines.append(f'      - "{pg_port}:{pg_port}"')
    mailhog_conf = config.get("mailhog", {})
    if mailhog_conf.get("enabled", False):
        mh_port = mailhog_conf.get("http_port", 8025)
        lines.append(f'      - "{mh_port}:{mh_port}"')

    lines += [
        f"    networks:",
        f"      - {NETWORK_NAME}",
        "    volumes:",
        "      - ./.resources/nginx_configs/generated.conf:/etc/nginx/conf.d/default.conf",
        "",
    ]
    return lines


def _mailhog_service(mailhog_conf):
    """Generate the MailHog service (SMTP catcher for dev environments)."""
    smtp_port = mailhog_conf.get("smtp_port", 1025)
    http_port = mailhog_conf.get("http_port", 8025)

    return [
        "  mailhog:",
        "    image: mailhog/mailhog:latest",
        "    restart: always",
        "    networks:",
        f"      - {NETWORK_NAME}",
        "    ports:",
        f'      - "{http_port}:8025"',
        "",
    ]


def _pgadmin_service(pgadmin_conf):
    port = pgadmin_conf.get("port", 5050)
    email = pgadmin_conf.get("email", "admin@admin.com")
    password = pgadmin_conf.get("password", "admin")

    return [
        "  pgadmin:",
        "    image: dpage/pgadmin4:latest",
        "    restart: always",
        "    environment:",
        f"      PGADMIN_DEFAULT_EMAIL: {email}",
        f"      PGADMIN_DEFAULT_PASSWORD: {password}",
        "    ports:",
        f'      - "{port}:80"',
        f"    networks:",
        f"      - {NETWORK_NAME}",
        "    volumes:",
        "      - pgadmin-data:/var/lib/pgadmin",
        "",
    ]


def _volumes(config):
    lines = [
        "volumes:",
    ]

    # DB volumes
    managed_dbs = get_managed_databases(config)
    for db_name in managed_dbs:
        lines.append(f"  {db_name}-data:")

    # Instance volumes
    for inst_name in config["instances"]:
        lines.append(f"  {inst_name}-web:")
        lines.append(f"  {inst_name}-data:")
        lines.append(f"  {inst_name}-py3:")
        lines.append(f"  {inst_name}-py:")

    # pgAdmin volume
    pgadmin_conf = config.get("pgadmin", {})
    if pgadmin_conf.get("enabled", False):
        lines.append("  pgadmin-data:")

    lines.append("")
    return lines


def _networks():
    return [
        "networks:",
        f"  {NETWORK_NAME}:",
        "    driver: bridge",
        "",
    ]
