#!/usr/bin/env python3

import subprocess
import sys
import click
from pathlib import Path

BASE_PATH = str(Path(__file__).resolve().parent.parent)
sys.path.insert(0, os.path.join(BASE_PATH, ".resources"))
from generators.config_loader import load_config


@click.command()
@click.argument("instance")
@click.option("-d", required=True, help="Database name")
@click.option("-i", required=True, help="Module to install/migrate")
def run_command(instance, d, i):
    config = load_config(BASE_PATH)
    if instance not in config["instances"]:
        click.echo(f"Error: instancia '{instance}' no existe")
        sys.exit(1)

    inst_conf = config["instances"][instance]
    odoo_version = inst_conf["odoo_version"]
    major = odoo_version.split(".")[0]
    container = f"odoo-{instance}"
    load_modules = f"base,web,views_migration_{major}"

    result = subprocess.run(
        [
            "docker", "exec",
            container,
            "odoo",
            "-i", i,
            "-d", d,
            f"--load={load_modules}",
            "--http-port=9999",
            "--workers=0",
            "--stop-after-init",
            "--without-demo=1",
        ],
    )
    sys.exit(result.returncode)

if __name__ == "__main__":
    run_command()
