#!/usr/bin/env python3

import json
import os
import sys
import click
from pathlib import Path

BASE_PATH = str(Path(__file__).resolve().parent.parent)
sys.path.insert(0, os.path.join(BASE_PATH, ".resources"))
from generators.config_loader import load_config, resolve_db_config, get_db_host


@click.command()
@click.argument("instance")
@click.option("-d", required=True, help="Database name")
@click.option("-l", default="admin", help="Login to reset")
@click.option("-p", "--password", default="admin", help="New password")
def run_command(instance, d, l, password):
    config = load_config(BASE_PATH)
    if instance not in config["instances"]:
        click.echo(f"Error: instancia '{instance}' no existe")
        sys.exit(1)

    inst_conf = config["instances"][instance]
    db_conf = resolve_db_config(inst_conf, config)
    db_host = get_db_host(inst_conf["database"], db_conf)
    db_user = db_conf["user"]
    db_password = db_conf["password"]
    db_port = db_conf["port"]
    container = f"odoo-{instance}"

    pw = f"'{password}'"
    login = f"'{l}'"
    os.system(
        f'docker exec -it -e PGPASSWORD={db_password} {container} psql --host {db_host} --port {db_port} -U {db_user} -d {d} -c "update res_users set password = {pw}, login = {login} where id=2;"'
    )


if __name__ == "__main__":
    run_command()
