#!/usr/bin/env python3

import os
import sys
import click
from pathlib import Path

BASE_PATH = str(Path(__file__).resolve().parent.parent)
sys.path.insert(0, os.path.join(BASE_PATH, ".resources"))
from generators.config_loader import load_config


@click.command()
@click.argument("instance")
@click.option("-d", default="testing", help="Database name")
@click.option("-t", "--test-tags", default="/binaural_accountant", help="Test tags")
@click.option("-i", "--install", default="l10n_ve,binaural_rate,account,binaural_accountant", help="Modules to install")
def run_command(instance, d, test_tags, install):
    config = load_config(BASE_PATH)
    if instance not in config["instances"]:
        click.echo(f"Error: instancia '{instance}' no existe")
        sys.exit(1)

    container = f"odoo-{instance}"
    command = (
        f"docker exec -uodoo -it {container} odoo --test-tags {test_tags} -d {d} -i {install} "
        "--without-demo=True --stop-after-init -c /home/odoo/.config/odoo.conf"
    )
    os.system(command)


if __name__ == "__main__":
    run_command()
