#!/usr/bin/env python3

import os
import click
from dotenv import load_dotenv


@click.command()
@click.option("-d", required=True, help="Database name")
@click.argument("args", nargs=-1)
def run_command(d, args):
    load_dotenv()
    PROJECT_NAME = os.getenv("PROJECT_NAME")
    modules_str = ' '.join(args)
    os.system(
        f"docker exec -it {PROJECT_NAME} odoo -d {d} -u {modules_str} --load-language=es_VE --stop-after-init"
    )

if __name__ == "__main__":
    run_command()
